### ISSUE TITLE
Web components demo broken?

### ISSUE THREAD

**Issue by thomasdavis** [vanillawc/wc-resume#6]
<img width="1269" alt="Screen Shot 2020-06-19 at 12 08 00 pm" src="https://user-images.githubusercontent.com/416209/85089276-94e82f80-b225-11ea-9725-bd0797a19373.png">

**Comment by evanplaice** [comment]
Fetch hasn't been working on WebComponents.dev for a while now. Not sure if this is intentional behavior or a bug. If it's the former I'll have to find another approach to hosting demos.

Either way, I opened [this issue](https://github.com/webcomponents-dev/webcomponents.dev/issues/20) on their repo

**Comment by thomasdavis** [comment]
Awesome

**Comment by gqio** [comment]
> Fetch hasn't been working on WebComponents.dev for a while now. Not sure if this is intentional behavior or a bug. If it's the former I'll have to find another approach to hosting demos.

Hi Evan and Thomas,

Sorry for this
This one was not intentional :)
Should be fixed now.

Thanks for reporting this.
